# Trabajo práctico integrador

**Nombre**: Angela Siles

## Primera Parte (Clase 1 y 2)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Primer ejercicio

Dada una matriz en formato *numpy array*, donde cada fila de la matriz representa un vector matemático, se requiere computar las normas $l_0$, $l_1$, $l_2$, $l_{\infty}$, según la siguientes definiciones:

\begin{equation}
    ||\mathbf{x}||^{p} = \bigg(\sum_{j=1}^{n}{|x_i|^p}\bigg)^{\frac{1}{p}}
\end{equation}

con los casos especiales para $p=0$ y $p=\infty$ siendo:

\begin{equation}
    \begin{array}{rcl}
        ||\mathbf{x}||_0 & = & \bigg(\sum_{j=1 \wedge x_j != 0}{|x_i|}\bigg)\\
        ||\mathbf{x}||_{\infty} & = & \max_{i}{|x_i|}\\
    \end{array}
\end{equation}

In [2]:
import numpy as np

def l0_norm(x):
    return np.count_nonzero(x)

def l1_norm(x):
    return np.sum(np.abs(x))

def l2_norm(x):
    return np.linalg.norm(x)

def linf_norm(x):
    return np.max(np.abs(x))

# Ejemplo de uso
matriz = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])
print("Matriz:")
print(matriz)

for i in range(matriz.shape[0]):
    print("Vector", i+1)
    print("Norma l0:", l0_norm(matriz[i]))
    print("Norma l1:", l1_norm(matriz[i]))
    print("Norma l2:", l2_norm(matriz[i]))
    print("Norma linf:", linf_norm(matriz[i]))

Matriz:
[[1 2 3]
 [4 5 6]
 [0 0 0]]
Vector 1
Norma l0: 3
Norma l1: 6
Norma l2: 3.7416573867739413
Norma linf: 3
Vector 2
Norma l0: 3
Norma l1: 15
Norma l2: 8.774964387392123
Norma linf: 6
Vector 3
Norma l0: 0
Norma l1: 0
Norma l2: 0.0
Norma linf: 0


### Segundo Ejercicio

En clasificación contamos con dos arreglos, la “verdad” y la “predicción”. Cada elemento de los arreglos pueden tomar dos valores, “True” (representado por 1) y “False” (representado por 0). Entonces podemos definir 4 variables:

* True Positive (TP): El valor verdadero es 1 y el valor predicho es 1
* True Negative (TN): El valor verdadero es 0 y el valor predicho es 0
* False Positive (FP): El valor verdadero es 0 y el valor predicho es 1
* False Negative (FN): El valor verdadero es 1 y el valor predicho es 0

A partir de esto definimos:

* Precision = TP / (TP + FP)
* Recall = TP / (TP + FN)
* Accuracy = (TP + TN) / (TP + TN + FP + FN)
 
Calcular las 3 métricas con Numpy y operaciones vectorizadas.

In [3]:
#lib
import numpy as np


In [4]:
# Definimos los arreglos de verdad y predicción

truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

In [5]:

# Calculamos los valores de TP, TN, FP y FN
TP = np.sum(np.logical_and(truth == 1, prediction == 1))
TN = np.sum(np.logical_and(truth == 0, prediction == 0))
FP = np.sum(np.logical_and(truth == 0, prediction == 1))
FN = np.sum(np.logical_and(truth == 1, prediction == 0))

# Calculamos las métricas de precision, recall y accuracy
precision = TP / (TP + FP)
recall = TP / (TP + FN)
accuracy = (TP + TN) / (TP + TN + FP + FN)

In [6]:

# Calculamos los valores de TP, TN, FP y FN
TP = np.sum(np.logical_and(truth == 1, prediction == 1))
TN = np.sum(np.logical_and(truth == 0, prediction == 0))
FP = np.sum(np.logical_and(truth == 0, prediction == 1))
FN = np.sum(np.logical_and(truth == 1, prediction == 0))

# Calculamos las métricas de precision, recall y accuracy
precision = TP / (TP + FP)
recall = TP / (TP + FN)
accuracy = (TP + TN) / (TP + TN + FP + FN)

In [7]:
# Imprimimos los resultados de las tres metricas
print("Precision:", precision)
print("Recall:", recall)
print("Accuracy:", accuracy)

Precision: 0.5
Recall: 0.5
Accuracy: 0.4
